### ISSUE TITLE
Disables Sidebars on WooThemes "NewsPress" Theme

### ISSUE THREAD

**Issue by Blackhawke** [woocommerce/woosidebars#44]
We're running WP 4.2.5 (waiting for some down time to attempt an upgrade to 4.3.1; over half of our plugins are _not_ listed as proven compatible with 4.3.1) and activating the plugin 1st deletes whatever widgets were in the theme sidebars, reverting them to default. 

That's fine, but the new sidebars created in the plugin _do nothing!_ No matter what I do, the default theme widgets are all that shows on the site. I've tried just about every other plugin out there like woosidebars, and if they create new sidebars, like woosidebars does, they have the same effect. They don't work, and only the theme default widgets show on the site. Rather surprising, really, as I figured the MOST compatible plugin I could install would be a Woo plugin.

Anyway, bug in plugin? Bug in theme? (More likely) Advice?

Thanks!

**Comment by mattyza** [comment]
Hi @Blackhawke,
It sounds like this may be a theme bug, because it's showing default widgets if you don't have any widgets set.

You could either modify the theme via a child theme, or could add an empty text widget to your sidebar, to hide the default widgets (although this would leave the open area where the widgets used to be).

I hope this helps. If it turns out the issue is in fact with the plugin, please do re-open this and let us know.
